#!/bin/bash -xeu

# This script prepares the lint environment in the same way the
# docker file does, but without the container as its runnign on
# single use node.

sudo apt-get update && sudo apt-get install -y \
  groovy2 python-pip build-essential python-dev libssl-dev \
  curl libffi-dev sudo git-core

./lint.sh
